# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae286e1f699b96866cdd1ba6fb292190bed2a260e3575ecff0f96681d9272902c61251a440b0b5f3a9c829a94475656ebad10957f987d2d46dad0468266301f0

test:
  secret_key_base: 33ae3b7288bbbef5d4684abd53cb3e885b6bbfd8c5b6c9cffd79a94ac43f12d5120151b745db9e59e06a0e0807184a67c7298194420ff8b53bee56081f2c876f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
